name: Flake-based CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@main
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v27
      - name: Cache Nix Store
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build derivation
        run: NIXPKGS_ALLOW_UNFREE=1 nix build --impure -L .
